# Generated by Django 3.0 on 2019-12-08 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vs_app', '0002_auto_20191203_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corrfits',
            name='aavso_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vs_app.AAVSOdata'),
        ),
        migrations.AlterField(
            model_name='corrfits',
            name='simbad_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vs_app.SimbadData'),
        ),
    ]
