# Generated by Django 3.0 on 2019-12-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vs_app', '0003_auto_20191208_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='simbaddata',
            name='DEC_PREC',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
