# Generated by Django 3.0 on 2019-12-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vs_app', '0004_simbaddata_dec_prec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simbaddata',
            name='DEC',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='simbaddata',
            name='RA',
            field=models.FloatField(),
        ),
    ]
